<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>License</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>License key for the edition of your web application.</p>
    <p>-;</p>
    <h2>License key attributes</h2>
    <ul class="g-help-list">
        <li><b>Registered in the name.</b> Username under which the web application edition is registered;</li>
        <li><b>E-mail.</b> User's email;</li>
        <li><b>Phone.</b> User's contact phone number;</li>
        <li><b>Date of registration.</b> Registration date of your web application version;</li>
        <li><b>Validity.</b> The license key validity period determines the timeframe during which the license key is considered valid and grants access to the web application's functionality;</li>
        <li><b>IP address.</b> The IP address of the server where your edition of the web application is installed;</li>
        <li><b>Domain name.</b> The domain name used to access the web application;</li>
        <li><b>Web application edition.</b> Web application revision identifier (name), indicating a specific configuration.</li>
    </ul>

    <h2>Possible mistakes</h2>
    <ul class="g-help-list">
        <li><b>Error getting key.</b> The API request failed to retrieve data in JSON format. This may indicate that the server did not return a valid JSON response—for example, due to an internal service error, authorization issues, or server problems.</li>
    </ul>
</article>